# Generated by Django 5.1 on 2025-02-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financas',
            options={'verbose_name': 'Finança', 'verbose_name_plural': 'Finanças'},
        ),
        migrations.AlterField(
            model_name='financas',
            name='entradas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financas',
            name='saidas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financas',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='financas',
            index=models.Index(fields=['nome'], name='financas_fi_nome_b059de_idx'),
        ),
    ]
