# Generated by Django 5.1 on 2025-02-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_financas_options_alter_financas_entradas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
