# Generated by Django 5.1 on 2025-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_alter_financas_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
